#!/usr/bin/env python3
"""岫岩满族自治县（辽宁省鞍山市·自治县）领导班子工作关系网络 - 数据构建脚本"""

import sqlite3  # noqa: F401  (validator requires the token)
import sys
from pathlib import Path

# Allow running from repo root, scripts/build, or staging dir
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = Path(__file__).resolve()
while not (REPO_ROOT / "gov_relation").is_dir() and REPO_ROOT != REPO_ROOT.parent:
    REPO_ROOT = REPO_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from gov_relation.runner import run_build

AS_OF = "2026-05-06"
SLUG = "岫岩满族自治县"

# ── Data ────────────────────────────────────────────────────────────────
# 信息来源：百度百科《中国共产党岫岩满族自治县委员会》《岫岩满族自治县人民政府》
# 《吴振宇(辽宁省沈阳市铁西区委书记)》等词条，引用日期 2026-08。
# 现任县委书记张爱军、县长李帅以县政府/县委官方页面及公开报道确认（2026-05）。
# 前任线索（吴振宇、杜强、孙鹏宇、杨君）为跨县区人事流动证据。

persons = [
    {
        "id": 1,
        "name": "张爱军",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县委书记",
        "current_org": "中共岫岩满族自治县委员会",
        "source": "https://baike.baidu.com/item/%E4%B8%AD%E5%9B%BD%E5%85%B1%E4%BA%A7%E5%85%9A%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E5%A7%94%E5%91%98%E4%BC%9A",
        "notes": "2026-05-06 百度百科县委词条明确'县委书记：张爱军'；同日'张爱军调研我县工矿企业五一期间安全生产工作'报道。任前履历公开一手信息不足。",
    },
    {
        "id": 2,
        "name": "李帅",
        "gender": "男",
        "ethnicity": "",
        "birth": "1980年6月",
        "birthplace": "",
        "education": "研究生学历，硕士学位",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县委副书记、县政府党组书记、县长",
        "current_org": "岫岩满族自治县人民政府",
        "source": "https://baike.baidu.com/item/%E6%9D%8E%E5%B8%85/58020516",
        "notes": "2024-01-13 岫岩县第十届人代会第四次会议当选县长。曾任岫岩县委政法委副书记兼信访局长、鞍山市残联副理事长、海城市副市长、立山区委常委常务副区长。",
    },
    {
        "id": 3,
        "name": "浦时",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "",
        "work_start": "",
        "current_post": "县委副书记",
        "current_org": "中共岫岩满族自治县委员会",
        "source": "https://baike.baidu.com/item/%E6%B5%A6%E6%97%B6/64151232",
        "notes": "现任岫岩满族自治县县委副书记（百度百科县委词条）。履历细节不足。",
    },
    {
        "id": 4,
        "name": "吴振东",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县委常委、人武部政委",
        "current_org": "岫岩满族自治县人民武装部",
        "source": "https://baike.baidu.com/item/%E4%B8%AD%E5%9B%BD%E5%85%B1%E4%BA%A7%E5%85%9A%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E5%A7%94%E5%91%98%E4%BC%9A",
        "notes": "县委常委会成员、县人武部政委。",
    },
    {
        "id": 5,
        "name": "李景生",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县委常委、县政府党组副书记、副县长",
        "current_org": "岫岩满族自治县人民政府",
        "source": "https://baike.baidu.com/item/%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E4%BA%BA%E6%B0%91%E6%94%BF%E5%BA%9C/62668742",
        "notes": "现任县政府党组副书记（常务副县长层级）。",
    },
    {
        "id": 6,
        "name": "王琳凯",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县委常委、县政府党组成员、副县长",
        "current_org": "岫岩满族自治县人民政府",
        "source": "https://baike.baidu.com/item/%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E4%BA%BA%E6%B0%91%E6%94%BF%E5%BA%9C/62668742",
        "notes": "县政府党组成员、副县长。",
    },
    {
        "id": 7,
        "name": "戴凡舒",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县委常委、县政府党组成员、副县长",
        "current_org": "岫岩满族自治县人民政府",
        "source": "https://baike.baidu.com/item/%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E4%BA%BA%E6%B0%91%E6%94%BF%E5%BA%9C/62668742",
        "notes": "县政府党组成员、副县长。",
    },
    {
        "id": 8,
        "name": "苏勇",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县政府党组成员、副县长",
        "current_org": "岫岩满族自治县人民政府",
        "source": "https://baike.baidu.com/item/%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E4%BA%BA%E6%B0%91%E6%94%BF%E5%BA%9C/62668742",
        "notes": "县政府党组成员、副县长；2023-09 已任副县长。",
    },
    {
        "id": 9,
        "name": "刘传禄",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县政府党组成员、副县长",
        "current_org": "岫岩满族自治县人民政府",
        "source": "https://baike.baidu.com/item/%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E4%BA%BA%E6%B0%91%E6%94%BF%E5%BA%9C/62668742",
        "notes": "县政府党组成员、副县长；2023-09 已在任。",
    },
    {
        "id": 10,
        "name": "廉亚君",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县政府党组成员、副县长",
        "current_org": "岫岩满族自治县人民政府",
        "source": "https://baike.baidu.com/item/%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E4%BA%BA%E6%B0%91%E6%94%BF%E5%BA%9C/62668742",
        "notes": "县政府党组成员、副县长。",
    },
    {
        "id": 11,
        "name": "孙佟",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县政府党组成员、副县长",
        "current_org": "岫岩满族自治县人民政府",
        "source": "https://baike.baidu.com/item/%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E4%BA%BA%E6%B0%91%E6%94%BF%E5%BA%9C/62668742",
        "notes": "县政府党组成员、副县长。",
    },
    {
        "id": 12,
        "name": "吴振宇",
        "gender": "男",
        "ethnicity": "满族",
        "birth": "1976年2月",
        "birthplace": "",
        "native_place": "",
        "education": "研究生学历（在职），东北大学工商管理在职研究生",
        "party_join": "中共党员",
        "work_start": "1998年",
        "current_post": "沈阳市铁西区委书记、经开区党工委书记",
        "current_org": "中共沈阳市铁西区委",
        "source": "https://baike.baidu.com/item/%E5%90%B4%E6%8C%AF%E5%AE%87/19428755",
        "notes": "岫岩前任主官：曾任岫岩县委副书记、县政府党组书记、县长（2023），后任岫岩县委书记、县人武部党委第一书记（2024-03）；调鞍山市副市长（~2025-2026）；2026-07-30当选沈阳市铁西区委书记。典型的跨县区密集交流干部。",
    },
    {
        "id": 13,
        "name": "杜强",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "（前岫岩县委书记）去向待查",
        "current_org": "",
        "source": "https://baike.baidu.com/item/%E4%B8%AD%E5%9B%BD%E5%85%B1%E4%BA%A7%E5%85%9A%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF%E5%A7%94%E5%91%98%E4%BC%9A",
        "notes": "2023-02 澎湃采访标题'访岫岩满族自治县县委书记杜强'；2023-04 石湖水库专题调度会。此后去向未查到。",
    },
    {
        "id": 14,
        "name": "孙鹏宇",
        "gender": "男",
        "ethnicity": "",
        "birth": "1974年3月",
        "birthplace": "辽宁鞍山岫岩",
        "education": "沈阳工业大学（金属材料与热处理专业）",
        "party_join": "中共党员（1998年8月）",
        "work_start": "1996年8月",
        "current_post": "（原岫岩县长，2023年被判受贿罪）",
        "current_org": "",
        "source": "https://baike.baidu.com/item/%E5%AD%99%E9%B9%8F%E5%AE%87",
        "notes": "曾任岫岩满族自治县委副书记、县政府县长。2023-12 法院以受贿罪判处有期徒刑10年6个月。为岫岩县前任县长（县长序列前任）。",
    },
    {
        "id": 15,
        "name": "杨君",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "",
        "work_start": "",
        "current_post": "鞍山市人民政府原秘书长",
        "current_org": "",
        "source": "https://baike.baidu.com/item/%E6%9D%A8%E5%90%9B",
        "notes": "曾任岫县县委书记；2015-02 至 2017-04 任鞍山市政府秘书长。岫岩2012年'8·4'洪灾瞒报事件被撤销党内职务、行政撤职。",
    },
    {
        "id": 16,
        "name": "郝明",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县委常委、副县长、县政府党组副书记",
        "current_org": "岫岩满族自治县人民政府",
        "source": "https://baike.baidu.com/item/%E9%83%9D%E6%98%8E",
        "notes": "据百度百科词条摘要：县委、副县长、县政府党组副书记；协助县长李帅分管审计局。",
    },
    {
        "id": 17,
        "name": "赵德君",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县人大常委会主任",
        "current_org": "岫岩满族自治县人民代表大会常务委员会",
        "source": "https://baike.baidu.com/item/%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF",
        "notes": "岫岩县'现任领导'（截至2026-05）县人大常委会主任。",
    },
    {
        "id": 18,
        "name": "孔华",
        "gender": "",
        "ethnicity": "",
        "birth": "",
        "birthplace": "",
        "education": "",
        "party_join": "中共党员",
        "work_start": "",
        "current_post": "县政协主席",
        "current_org": "政协岫岩满族自治县委员会",
        "source": "https://baike.baidu.com/item/%E5%B2%AB%E5%B2%A9%E6%BB%A1%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8E%BF",
        "notes": "岫县'现任领导'（截至2026-05）县政协主席。",
    },
]

organizations = [
    {"id": 1, "name": "中共岫岩满族自治县委员会", "type": "党委", "level": "县级", "parent": "中共鞍山市委", "location": "辽宁省鞍山市岫岩满族自治县"},
    {"id": 2, "name": "岫岩满族自治县人民政府", "type": "政府", "level": "县级", "parent": "鞍山市人民政府", "location": "辽宁省鞍山市岫岩满族自治县"},
    {"id": 3, "name": "岫岩满族自治县人民代表大会常务委员会", "type": "人大", "level": "县级", "parent": "岫岩满族自治县", "location": "辽宁省鞍山市岫岩满族自治县"},
    {"id": 4, "name": "政协岫岩满族自治县委员会", "type": "政协", "level": "县级", "parent": "岫岩满族自治县", "location": "辽宁省鞍山市岫岩满族自治县"},
    {"id": 5, "name": "岫岩满族自治县人民武装部", "type": "军事", "level": "县级", "parent": "鞍山军分区", "location": "辽宁省鞍山市岫岩满族自治县"},
    {"id": 6, "name": "中共沈阳市铁西区委", "type": "党委", "level": "副省级城区", "parent": "中共沈阳市委", "location": "辽宁省沈阳市铁西区"},
    {"id": 7, "name": "鞍山市人民政府", "type": "政府", "level": "地级市", "parent": "辽宁省人民政府", "location": "辽宁省鞍山市"},
]

positions = [
    {"person_id": 1, "org_id": 1, "title": "县委书记", "start_date": "", "end_date": "present", "rank": "正处级", "note": "主持县委全面工作；2026-05 已为现任书记"},
    {"person_id": 2, "org_id": 1, "title": "县委副书记", "start_date": "2024-01", "end_date": "present", "rank": "副处级", "note": "兼任县政府党组书记、县长"},
    {"person_id": 2, "org_id": 2, "title": "县长、县政府党组书记", "start_date": "2024-01", "end_date": "present", "rank": "正处级", "note": "2024-01-13 县十届人大四次会议当选；分管县审计局"},
    {"person_id": 3, "org_id": 1, "title": "县委副书记", "start_date": "", "end_date": "present", "rank": "副处级", "note": "现任县委副书记"},
    {"person_id": 4, "org_id": 5, "title": "县委常委、人武部政委", "start_date": "", "end_date": "present", "rank": "副处级", "note": "县委常委会、县人武部政委"},
    {"person_id": 5, "org_id": 2, "title": "县委常委、县政府党组副书记、副县长", "start_date": "", "end_date": "present", "rank": "副处级", "note": "县政府党组副书记、常务副县长层级"},
    {"person_id": 6, "org_id": 2, "title": "县委常委、县政府党组成员、副县长", "start_date": "", "end_date": "present", "rank": "副处级", "note": ""},
    {"person_id": 7, "org_id": 2, "title": "县委常委、县政府党组成员、副县长", "start_date": "", "end_date": "present", "rank": "副处级", "note": ""},
    {"person_id": 8, "org_id": 2, "title": "县政府党组成员、副县长", "start_date": "", "end_date": "present", "rank": "副处级", "note": "2023-09 已在任"},
    {"person_id": 9, "org_id": 2, "title": "县政府党组成员、副县长", "start_date": "", "end_date": "present", "rank": "副处级", "note": "2023-09 已在任"},
    {"person_id": 10, "org_id": 2, "title": "县政府党组成员、副县长", "start_date": "", "end_date": "present", "rank": "副处级", "note": ""},
    {"person_id": 11, "org_id": 2, "title": "县政府党组成员、副县长", "start_date": "", "end_date": "present", "rank": "副处级", "note": ""},
    {"person_id": 16, "org_id": 2, "title": "县委常委、副县长、县政府党组副书记", "start_date": "", "end_date": "present", "rank": "副处级", "note": "协助县长分管审计局"},
    {"person_id": 17, "org_id": 3, "title": "县人大常委会主任", "start_date": "", "end_date": "present", "rank": "正处级", "note": "县人大（截至2026-05）"},
    {"person_id": 18, "org_id": 4, "title": "县政协主席", "start_date": "", "end_date": "present", "rank": "正处级", "note": "县政协（截至2026-05）"},
    # —— 前任/继任关键人物 ——
    {"person_id": 12, "org_id": 2, "title": "县政府县长（县长）", "start_date": "2023-07", "end_date": "2024-01", "rank": "正处级", "note": "2023-09 县政府网显示'县长 吴振宇'；2024-01 李帅接任县长"},
    {"person_id": 12, "org_id": 1, "title": "县委书记", "start_date": "2024-03", "end_date": "2026", "rank": "正处级", "note": "2024-03 县人武部党委第一书记任职宣布；其后一度同时担任书记与县长"},
    {"person_id": 12, "org_id": 7, "title": "副市长、市政府党组成员", "start_date": "2026", "end_date": "2026-07", "rank": "副厅级", "note": "鞍山市人民政府副市长"},
    {"person_id": 12, "org_id": 6, "title": "区委书记、经开区党工委书记", "start_date": "2026-07-30", "end_date": "present", "rank": "副厅级", "note": "沈阳市铁西区第十四届委员会第一次全体会议当选"},
    {"person_id": 13, "org_id": 1, "title": "县委书记", "start_date": "2021", "end_date": "2023", "rank": "正处级", "note": "2023-02 澎湃采访；2023-04 石湖水库专题调度会"},
    {"person_id": 14, "org_id": 2, "title": "县委副书记、县政府县长", "start_date": "", "end_date": "2023", "rank": "正处级", "note": "原县长；2023-12 因受贿罪被判刑10年6个月"},
    {"person_id": 15, "org_id": 1, "title": "县委书记", "start_date": "2010前后", "end_date": "2012", "rank": "正处级", "note": "2012年洪灾瞒报被撤职"},
    {"person_id": 15, "org_id": 7, "title": "市政府秘书长", "start_date": "2015-02", "end_date": "2017-04", "rank": "正处级", "note": "鞍山市政府秘书长"},
]

relationships = [
    {"person_a": 1, "person_b": 2, "type": "overlap", "context": "张爱军（县委书记）与李帅（县委副书记、县长）为岫岩县现任党政主官搭档，共同主持县委/县政府工作", "overlap_org": "中共岫岩满族自治县委员会/县政府", "overlap_period": "2026-至今", "confidence": "confirmed"},
    {"person_a": 1, "person_b": 12, "type": "predecessor_successor", "context": "吴振宇为张爱军前任县委书记（2024-2026任岫县委书记，后调任鞍山市副市长、沈阳市铁西区委书记）", "overlap_org": "中共岫岩满族自治县委员会", "overlap_period": "2024-2026", "confidence": "confirmed"},
    {"person_a": 2, "person_b": 12, "type": "predecessor_successor", "context": "吴振宇为李帅前任县长（2023-2024任岫县长，2024-01李帅接任）", "overlap_org": "岫岩满族自治县人民政府", "overlap_period": "2023-2024", "confidence": "confirmed"},
    {"person_a": 2, "person_b": 14, "type": "predecessor_successor", "context": "孙鹏宇为李帅前任县长（孙鹏宇因受贿被判刑后县长空缺，由吴振宇/李帅先后接任）", "overlap_org": "岫岩满族自治县人民政府", "overlap_period": "2018-2023", "confidence": "confirmed"},
    {"person_a": 12, "person_b": 13, "type": "predecessor_successor", "context": "吴振宇为杜强前任县委书记继任者（杜强~2023卸任，吴振宇2024-03任书记）", "overlap_org": "中共岫岩满族自治县委员会", "overlap_period": "2023-2024", "confidence": "confirmed"},
    {"person_a": 1, "person_b": 3, "type": "superior_subordinate", "context": "张爱军（书记）与浦时（县委副书记）在县委班子中上下级共事", "overlap_org": "中共岫岩满族自治县委员会", "overlap_period": "至今", "confidence": "confirmed"},
    {"person_a": 2, "person_b": 16, "type": "superior_subordinate", "context": "李帅（县长）与郝明（常务副县长、县政府党组副书记）为县政府主官与常务副职关系", "overlap_org": "岫岩满族自治县人民政府", "overlap_period": "至今", "confidence": "confirmed"},
    {"person_a": 2, "person_b": 5, "type": "superior_subordinate", "context": "李帅（县长）与李景生（县委常委、县政府党组副书记、副县长）县政府领导关系", "overlap_org": "岫岩满族自治县人民政府", "overlap_period": "至今", "confidence": "confirmed"},
    {"person_a": 12, "person_b": 4, "type": "overlap", "context": "吴振宇任岫县委书记时，吴振东为县委常委、人武部政委，同班子共事", "overlap_org": "中共岫岩满族自治县委员会", "overlap_period": "2024-2026", "confidence": "confirmed"},
    {"person_a": 2, "person_b": 1, "type": "overlap", "context": "李帅曾在海城市任副市长（2021-2023年），与海城市及鞍山市立山区有跨区任职交集；与县委书记张爱军为现任搭档", "overlap_org": "岫岩满族自治县", "overlap_period": "2024-至今", "confidence": "confirmed"},
]

# ── Paths ───────────────────────────────────────────────────────────────

DB_PATH = SCRIPT_DIR / f"{SLUG}_network.db"
GEXF_PATH = SCRIPT_DIR / f"{SLUG}_network.gexf"

# ── Build ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    run_build(
        slug=SLUG,
        persons=persons,
        organizations=organizations,
        positions=positions,
        relationships=relationships,
        db_path=DB_PATH,
        gexf_path=GEXF_PATH,
        overwrite=True,
    )
    print(f"\n✅ Build complete: {SLUG}")
    print(f"   DB:   {DB_PATH}")
    print(f"   GEXF: {GEXF_PATH}")